### ISSUE TITLE
[Feature request] Options with Mod Menu

### ISSUE THREAD

**Issue by AuracleTech** [Plastoid501/movement-in-gui#1]
It could be nice to get options like "Enable in creative : On" or "Enable in chat : Off"
Currently it's ON in chat, so if I place myself in a safe place and start typing, I move around, very scary

**Comment by Plastoid501** [comment]
fixed this issue.
Thank you for your report.
## Changes
- when open chatScreen, OptionsScreen and etc, unfunctinally this mod.
- Add config(can open config screen from modmenu)

**Comment by AuracleTech** [comment]
![image](https://github.com/user-attachments/assets/b7ee2e0c-4a17-451c-8fb2-4f037761f2a1)

Currently we can't disable it while typing in chat, and the mod menu isn't available yet I still have to use config
Is the mod updated?

**Comment by Plastoid501** [comment]
I figured that no one would want to enable the mod on chat screen, so I have made it so that it will not accept operations on chat screen without config. If you want to activate it with chat screen, I will update the mod to add config and allow you to select it.

**Comment by AuracleTech** [comment]
Ok no problem, just tested everything seems fine :]
Thank you for your nice plugin
